### ISSUE TITLE
Card component

### ISSUE THREAD

**Issue by oy-gen** [oy-gen/capstone-project#1]
### Value description
As a user
I want to see the offered products shown as a list of cards
so that I have all the information I need. 

### Description
![Screen Shot 2022-05-23 at 10 57 56](https://user-images.githubusercontent.com/102030428/169783059-d759984d-5c46-46cf-b58c-20330ac8a961.png)

### Acceptance Criteria

- [x]  Picture of products should be shown
- [x]  Product name should be shown
- [x]  Wholesale price should be shown
- [x]  recommended retail price should be shown

### Tasks
 
- [x]  Create a new branch
- [x]  Create a a data set that will be displayed in the cards
- [x]  Create Card component
- [x]  Create Cardlist component
- [x]  Add global styles
- [x]  Show several product cards with data in a list

### Complexity
low

**Comment by oy-gen** [comment]
### Value description

As a *user* I want to *save a list of recipies*
so that *I don't forget them*.

### Desription
![Screen Shot 2022-05-18 at 15 38 33](https://user-images.githubusercontent.com/102030428/169052724-cc255f97-740e-4b16-a3af-9971f05a7fa8.png)

### Acceptance criteria
- [ ] must have a counter
- [ ] must have a +/- button
- [ ] remove button optional
- [ ] @mobile: swipe right to add, swipe left to remove

**Comment by marcbendixen** [comment]
Well done 🚀 
As we've already discussed, this looks good for a first user-story.
