### ISSUE TITLE
Add header section with logo

### ISSUE THREAD

**Issue by oy-gen** [oy-gen/capstone-project#10]
### Value description

As a user
I want to see the shop's logo at the top of the screen, so I know I am in the right shop. 

### Description

![Screen Shot 2022-05-28 at 16 34 44](https://user-images.githubusercontent.com/102030428/170829965-4cb4288e-abb3-4a6c-99c0-61ff9bb23c18.png)

### Acceptance Criteria

- [x]  the logo of the shop should be shown in the header.
- [x]  the header should always stay in the foreground and stay in position.

### Tasks
 
- [x]  Create a new branch
- [x]  Create a header element
- [x]  Create a logo container with maximum sizes 
- [x]  Place the logo centered

### Complexity
low

**Comment by UrsulaMontag** [comment]
I would replace header-navigation with header-element in the second task. You only make a headline in the header and no navigation. 
Your task section could be a bit more detailed. Should the header only appear on one page? Is it still a 'difficulty: low' feature if you want to show the header on every page?
