### ISSUE TITLE
Add checkout page

### ISSUE THREAD

**Issue by oy-gen** [oy-gen/capstone-project#12]
### Value description

As a user
I want to see a checkout page 
so I can see the final price of my order including taxes and shipping cost. 

### Description
![Screen Shot 2022-05-30 at 15 57 41](https://user-images.githubusercontent.com/102030428/171007510-e2a42789-3429-4d5b-b1fa-907ae95158c6.png)

### Acceptance Criteria

- [x]  each product has a name
- [x]  each product has a product number
- [x]  each product has an amount
- [x]  each product has a unit price
- [x]  each product has a total unit price
- [x]  a subtotal is shown below the table
- [x]  shipping costs are shown below the table
- [x]  taxes are added on everything
- [x]  the final price is listed

### Tasks
 
- [x]  Create a new branch
- [x]  Create a new page
- [x]  create a table

### Complexity
medium

**Comment by cat-miller** [comment]
Looks good to me!
