### ISSUE TITLE
Add checkout section

### ISSUE THREAD

**Issue by oy-gen** [oy-gen/capstone-project#13]
### Value description

As a user
I want to confirm my purchase,
so I that my order is sent out. 

### Acceptance Criteria

- [x] the section must have a "confirm" button
- [x] when the button is clicked the order is transmitted

### Tasks
 
- [x]  Create a new branch
- [x] create a section
- [x] create a button
- [ ] #21

### Complexity
medium
