### ISSUE TITLE
Confirm Purchase Notification

### ISSUE THREAD

**Issue by oy-gen** [oy-gen/capstone-project#14]
### Value description

As a user
I want to be notified about my purchase confirmation
so I know that my order is transmitted successfully. 

### Acceptance Criteria

- [x] the section must have a "confirm" button.
- [x] when the button is clicked a popup notification is shown.

### Tasks
 
- [x] Create a new branch
- [x] create a section
- [x] create a button
- [x] create notification

### Complexity
low
