### ISSUE TITLE
Add Adress Form

### ISSUE THREAD

**Issue by oy-gen** [oy-gen/capstone-project#15]
### Value description

As a user
I want to add my contact information,
so that the order can be shipped to me.

### Acceptance Criteria

- [x]  a form is shown in a modal
- [x]  the modal can be opened with a button
- [x]  the form has the following text fields:
  - first name
  - last name
  - email adress
  - company (optional)
  - extra name field (optional)
  - street and house number
  - zip
  - city
  - country
 - [x] A submit button is shown below the form 

### Tasks
 
- [x]  Create a new branch
- [x]  Create a button
- [x]  Create a modal 
- [x]  Create a form in the modal
- [x]  Add user information to Store  

### Complexity
medium

**Comment by Chaosfuchs** [comment]
You should create a wireframe. So that one can better imagine how you imagine it approximately :)
