### ISSUE TITLE
Store contact information

### ISSUE THREAD

**Issue by oy-gen** [oy-gen/capstone-project#16]
### Value description

As a user
I want to store my contact information,
so that I don't have to fill out the form again after reload.

### Acceptance Criteria

- [ ]  user information is stored in local storage
- [ ]  user information is loaded from local storage

### Tasks
 
- [ ]  create a new branch
- [ ]  store user information in local Storage

### Complexity
low
