### ISSUE TITLE
User Log-in

### ISSUE THREAD

**Issue by oy-gen** [oy-gen/capstone-project#17]
### Value description

As a user
I want to log in,
so I can get access to the restricted b2b experience.

### Description

<img width="380" alt="Screen Shot 2022-06-13 at 12 16 59" src="https://user-images.githubusercontent.com/102030428/173332880-95dc8dfa-a871-4f83-9d03-8234b122093c.png">

### Acceptance Criteria

- [ ] show header with shop logo
- [ ] show user login form
- [ ] show login/start button

### Tasks
 
- [ ]  create a new branch
- [ ] create a new page
- [ ] add background image
- [ ] add logo header
- [ ]  add login form
- [ ]  add login button
- [ ] add authorization (next.Auth)

### Complexity
low

**Comment by Chaosfuchs** [comment]
I would write under acceptance criteria perhaps still, which possibilities must be there for announcing :) So for example Github, Google or so

Also you should write in the tasks that if you use for example Github to log in, that you also have to create this in Github itself :)

**Comment by Chaosfuchs** [comment]
Otherwise it looks really good :) Keep it up!

**Comment by mariagg8** [comment]
Looks good! A minor comment, i would use the term Log In, instead of Start.
