### ISSUE TITLE
Add form edit function

### ISSUE THREAD

**Issue by oy-gen** [oy-gen/capstone-project#24]
### Value description
As a user
I want to edit my address,
so I can correct the typo mistake that I have made before.

### Acceptance Criteria

- [x]  an edit-button should be shown
- [x]  the form should show the previously entered address
- [x] the text should be editable
- [x] there should be a save/confirm button

### Tasks
 
- [x]  create a new branch
- [x]  create an edit button
- [x]  make previous entry editable in the form
- [x]  create save button

**Comment by CJAkkuec** [comment]
> so I can correct the typo mistake that I have made before
Another use case (but probably for client databases rather than one-time purchases) would be a change of address due to a move, etc. 

I'd argue that the user should be able to change/edit any input they've made (name, etc), so I'm not sure why you've chosen to single out only the address? :)
