### ISSUE TITLE
Add Database

### ISSUE THREAD

**Issue by oy-gen** [oy-gen/capstone-project#25]
### Value description

As a user
I want my log-in data to be safely stored on a data-base,
so I can  login from any device.

### Acceptance Criteria

- [x] login is possible on different devices

### Tasks
 
- [x]  create a new branch
- [x]  add mongoDB
- [x]  add user model

### Complexity
medium
