### ISSUE TITLE
Add price adjustment page

### ISSUE THREAD

**Issue by oy-gen** [oy-gen/capstone-project#28]
### Value description

As a selling user
I want to adjust the wholesale prices of my products, so the logged in reselling user can see and compare them with the retail prices.

### Description
![Screen Shot 2022-06-13 at 13 52 46](https://user-images.githubusercontent.com/102030428/173789770-312b1d9c-9f0f-4862-a568-6fa18c8b25df.png)

### Acceptance Criteria

- [ ]  each product should be displayed
   - [ ] with name
   - [ ] with retail price
- [ ]  an input field should be visible next to each product.
- [ ]  a confirm button should save the entries.

### Tasks
 
- [ ]  Create a new branch
- [ ]  Create a new page
- [ ]  Create a seller's login data
- [ ] Create a product list
- [ ] Create a form 
- [ ] Create an input field for each product
- [ ] Create a submit-button
- [ ] Create logic that saves the input value in useStore

### Complexity
medium

**Comment by Chaosfuchs** [comment]
LGTM 🚀
