### ISSUE TITLE
Add plus/minus button

### ISSUE THREAD

**Issue by oy-gen** [oy-gen/capstone-project#3]
### Value description

As a user
I want to add and subtract the quantity of the product I want to buy,
I also want to reset the amount with one click.

### Description
![Screen Shot 2022-05-24 at 09 48 07](https://user-images.githubusercontent.com/102030428/169978419-c99c9b65-8ec9-4ac3-880d-1d37c8c3442c.png)

### Acceptance Criteria

- [ ]  Initial amount should be zero for each product.
- [ ]  quantity selector should have a plus and a minus button to add and subtract quantity.
- [ ]  The quantity should be displayed between the plus und minus button.
- [ ]  The quantity display must be wide enough to show double-digit numbers.
- [ ]  An additional remove-button should be positioned below the quantity selector.

### Tasks
 
- [ ]  Create a new branch
- [ ]  Create a quantity selector component
- [ ]  Create a remove button component
- [ ]  position both components in the cards component

### Complexity
low
