### ISSUE TITLE
Add shipping conditions page

### ISSUE THREAD

**Issue by oy-gen** [oy-gen/capstone-project#30]
### Value description

As a seller
I want to add shipping prices and conditions, so that the checkout prices  are calculated correctly for the buyer. 

### Description
<img width="407" alt="Screen Shot 2022-06-18 at 10 46 07" src="https://user-images.githubusercontent.com/102030428/174430209-39384b38-a1f6-4b91-8487-09059b7abc05.png">

### Acceptance Criteria

- [ ]  domestic shipping per parcel input should be shown
- [ ]  international shipping per parcel input should be shown
- [ ] Maximum products per parcel should be shown
- [ ]  save/confirm button should be shown

### Tasks
 
- [ ]  Create a new branch
- [ ]  Create a new page
- [ ] Create a form
- [ ] Create input fields
- [ ] Create confirm button

### Complexity
low

**Comment by Luxa23** [comment]
hi @oy-gen,
ich habe ein paar kleinere Anmerkungen:
- statt selling und buying user, würde ich einfach schreiben "as seller" und "buyer". Das finde ich weniger verwirrend und letztendlich wissen ja alle Beteiligten, das es sich um ein digitales Produkt mit Usern handelt.
- "products per parcel" : ist das die min. oder max. Menge an Produkten pro Paket, die du anlegen willst? Es gibt ja auch verschieden große Pakete, da würden sich die Zahlen ja ändern. Kann immer eine beliebige Anzahl der Produkte versendet werden?

**Comment by oy-gen** [comment]
Das mit products per parcel ist ein sehr guter Punkt, danke! Natürlich ist die maximale Anzahl pro Paket gemeint, das schreibe ich noch dazu. Ansonsten habe ich die Versandkosten-Details einfach und pauschal gehalten, um keine Doktorarbeit darüber schreiben zu müssen :)
