### ISSUE TITLE
Add visual effect for quantity

### ISSUE THREAD

**Issue by oy-gen** [oy-gen/capstone-project#31]
### Value description

As a user
I want to see which and how many products I have in my cart , so I can estimate and compare the amounts more quickly and intuitively. 

### Description
![Screen Shot 2022-06-18 at 11 07 20](https://user-images.githubusercontent.com/102030428/174431134-d6cc3c49-ddce-49e3-a0e6-91584d2a3650.png)

### Acceptance Criteria
- [ ]  Show a colored background element for each product. 
- [ ]  The background element is growing according to the amount in the cart.

### Tasks
 
- [ ] create a new branch
- [ ] create a colored div
- [ ] create logic that makes it grow with quantity.

### Complexity
low

**Comment by Luxa23** [comment]
hi @oy-gen,
ich verstehe, dass du es den Usern leichter machen willst, einen Überblick über die Mengen im Warenkorb zu erlangen. Als ich den Screen gerade das erste Mal gesehen habe, habe ich nur gar nicht verstanden, wozu der Hintergrund da ist. Ich dachte ehrlich gesagt, das sei ein Fehler. Es fiel mir also schwer, ihn mit den Mengen im Warenkorb zu assoziieren. Vielleicht gibt es eine andere Art und Weise das darzustellen und ich würde auch wagen zu fragen, ob man das überhaupt braucht. Aber es ist deine App und die Idee an sich finde ich gut :) 
In anderem Rahmen hätte ich vielleicht einen A/B-Test vorgeschlagen ;)

**Comment by oy-gen** [comment]
Ich denke, sobald man mit den Buttons interagiert und ein visuelles Feedback bekommt, sollte das Konzept augenblicklich klar werden. Ich probiere es aus, wir werden sehen
