### ISSUE TITLE
Fetch product info from shopify

### ISSUE THREAD

**Issue by oy-gen** [oy-gen/capstone-project#32]
### Value description

As a user
I want to see all products up-to-date,
so I know what I buy.

### Acceptance Criteria

- [x] See following product info
  - [x] image
  - [x] name
  - [x] RRP price
  - [x] GTIN/Barcode 
  - [x] description

### Tasks
 
- [x]  create a new branch
- [x]  add fetch function

### Complexity
high
