### ISSUE TITLE
Add "more info" function

### ISSUE THREAD

**Issue by oy-gen** [oy-gen/capstone-project#6]
### Value description

As a user
I want to see more information about the product when clicking on the product card. I also want to hide this information by clicking again.

### Description
![Screen Shot 2022-05-25 at 10 42 20](https://user-images.githubusercontent.com/102030428/170220652-0af82400-b33a-465a-9d2e-964f384bda5e.png)

### Acceptance Criteria

- [x]  Each product can be folded/unfolded separately.
- [x]  "more info" should change to "less info" when unfolded.
- [x]  The additional info should contain the product text.
- [x]  The additional info should contain the product's unique barcode, which is also used as a key-id.

### Tasks
 
- [x]  Create a new branch
- [x]  Create a "show/hide info" button.
- [x]  load product text and barcode from product data base into a container
- [x]  create a visibility toggle-function for the container.

### Complexity
low

**Comment by marcbendixen** [comment]
Hey 👋 
I like this a lot. This is a really good user story. Well structured and totally clear to me.
Also a nice design already. I have nothing to add here 👍
