### ISSUE TITLE
Add dynamic total price section

### ISSUE THREAD

**Issue by oy-gen** [oy-gen/capstone-project#8]
### Value description

As a user
I want to see a dynamically calculated total price of all selected products, so I know how much the order will cost me. I also want to see the total product quantity, so I know how much storage I need to reserve in my retail store.

### Description

![Screen Shot 2022-05-28 at 16 13 31](https://user-images.githubusercontent.com/102030428/170829188-502456b7-2a89-4837-88e8-1d1f7c5d3e6d.png)

### Acceptance Criteria

- [x]  the section should have a neutral background.
- [x]  Total price should be displayed first.
- [x]  Total product quantity should be displayed as second.

### Tasks
 
- [x]  Create a new branch
- [x]  Create a navigation section
- [x]  Create a total price element
- [x] Create a total quantity element
- [x]  Create useStore calculation functions

### Complexity
medium

**Comment by cat-miller** [comment]
Looks good to me! :)
