### ISSUE TITLE
Add header with logo

### ISSUE THREAD

**Issue by oy-gen** [oy-gen/capstone-project#9]
### Value description

As a user
I want to see the shop's logo at the top of the screen, so I know I am in the right shop. 

### Description

![Screen Shot 2022-05-28 at 16 34 44](https://user-images.githubusercontent.com/102030428/170829965-4cb4288e-abb3-4a6c-99c0-61ff9bb23c18.png)

### Acceptance Criteria

- [ ]  the logo of the shop should be shown in the header.
- [ ]  the header should always stay in the foreground and stay in position.

### Tasks
 
- [ ]  Create a new branch
- [ ]  Create a header navigation element
- [ ]  Creae a logo container with maximum sizes 
- [ ]  Place the logo centered

### Complexity
low
